# Додаткове завдання з pandas
Вітаю! В цьому завданні будемо працювати з даними з опитування щодо зарплат ІТ спеціалістів на рексурсі DOU від грудня 2022 року. Впевнена, це буде цікаве дослідження, а заразом і практика pandas :)
Цей аналіз може бути корисним людині, яка обирає напрям роботи в ІТ і хоче зрозуміти тенденції. За якісного виконання цього аналізу, цей проєкт можна сміливо додавати у Ваше портфоліо!

1. Зчитайте дані з файлу `2022_dec_raw.csv`. Увага! Тут необхідно використати аргумент `pd.read_csv` `sep=';'`, бо розділювач в даних - крапка з комою.

In [1]:
import pandas as pd

df = pd.read_csv('../data/2022_dec_raw.csv', sep=';')

In [2]:
df

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
0,11.30.2022 10:26:37,"Так, працюю part-time",В Україні,Івано-Франківськ чи область,4000,Чоловік,29,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blockchain,Стартап,8 років
1,11.30.2022 10:26:39,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,NaN,Чоловік,36,"Вища (бакалавр, спеціаліст, магістр)",Немає,Advanced,...,NaN,NaN,NaN,NaN,NaN,Ruby,Full Stack розробка,Public services / Government,Продуктова,3 роки
2,11.30.2022 10:26:58,"Так, працюю full-time",В Україні,Київ чи область,2500,Чоловік,34,"Вища (бакалавр, спеціаліст, магістр)",Немає,Elementary,...,NaN,NaN,NaN,NaN,NaN,C# / .NET,Full Stack розробка,"Adtech / Advertising, Security, Telecom",Продуктова,4 роки
3,11.30.2022 10:27:31,"Так, працюю full-time",В Україні,Львів чи область,500,Жінка,23,"Вища (бакалавр, спеціаліст, магістр)",Немає,Pre-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Telecom,Продуктова,Пів року
4,11.30.2022 10:27:34,"Ні, тимчасово не працюю",В Україні,Житомир чи область,2800,Жінка,33,"Вища (бакалавр, спеціаліст, магістр)",Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Automotive,Продуктова,6 років
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13310,01.09.2023 11:01,"Так, працюю full-time",В Україні,Харків чи область,4000,Чоловік,25,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,"Так, використовую",TypeScript,QA,Medtech / Healthcare,Продуктова,6 років
13311,01.09.2023 11:14,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,3500,Чоловік,28,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,JavaScript,Front-end розробка,Blockchain,Аутсорсингова,5 років
13312,01.09.2023 11:19,"Так, працюю full-time",В Україні,Дніпро чи область,1930,Чоловік,25,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Blockchain, Fintech / Banking, Mobile",Аутсорсингова,3 роки
13313,01.09.2023 11:28,"Так, працюю full-time",В Україні,Одеса чи область,4500,Чоловік,31,Середня,Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,NaN,JavaScript,Full Stack розробка,Mobile,Продуктова,8 років
13314,01.09.2023 11:38,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,4200,Чоловік,32,"Вища (бакалавр, спеціаліст, магістр)",Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,NaN,PHP,Back-end розробка,"High Load Systems, Media",Аутстафінгова,11 років

2. Які колонки мають дані?

In [3]:
# Загальна кількість записів і атрибутів
n_rows, n_columns = df.shape
print(f'Кількість записів: {n_rows}, кількість атрибутів: {n_columns}')

Кількість записів: 13315, кількість атрибутів: 28

In [4]:
# Всі атрибути датасету
df.columns

Index(['Timestamp', 'Ви працюєте зараз в ІТ?', 'Де ви зараз живете? ',
       'В якій області ви зараз живете?',
       'Зарплата у $$$ за місяць, лише ставка після сплати податків',
       'Ваша стать', 'Ваш вік', 'Яка у вас освіта?',
       'Чи є у вас науковий ступінь? ', 'Знання англійської мови',
       'Оберіть вашу посаду', 'Ваш тайтл', 'Ваша спеціалізація',
       'Вкажіть вашу спеціалізацію', 'Оберіть вашу спеціалізацію',
       'Ваша посада', 'Оберіть вашу посаду2', 'Ваша посада3', 'Ваша посада4',
       'Ваша посада5', 'Ваша посада6', 'Ваша посада7',
       'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',
       'Основна мова програмування', 'Вкажіть вашу основну спеціалізацію',
       'В якій сфері працюєте?', 'Тип компанії',
       'Загальний стаж роботи за спеціальністю'],
      dtype='object')

In [5]:
# Список колонок, які мають дані + кількість виповнених даних - Всі атрибути мають дані, але деякі з них мають NaN!
df.notna().sum()

Timestamp                                                                     13315
Ви працюєте зараз в ІТ?                                                       13315
Де ви зараз живете?                                                           13315
В якій області ви зараз живете?                                               11538
Зарплата у $$$ за місяць, лише ставка після сплати податків                   13288
Ваша стать                                                                    13315
Ваш вік                                                                       13315
Яка у вас освіта?                                                             13315
Чи є у вас науковий ступінь?                                                  13204
Знання англійської мови                                                       13315
Оберіть вашу посаду                                                           13315
Ваш тайтл                                                                     13315
Ваша спеціалізація                                                              159
Вкажіть вашу спеціалізацію                                                     2364
Оберіть вашу спеціалізацію                                                      486
Ваша посада                                                                     305
Оберіть вашу посаду2                                                            560
Ваша посада3                                                                    821
Ваша посада4                                                                    485
Ваша посада5                                                                    288
Ваша посада6                                                                    353
Ваша посада7                                                                    116
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?     4874
Основна мова програмування                                                     9060
Вкажіть вашу основну спеціалізацію                                             9059
В якій сфері працюєте?                                                        13315
Тип компанії                                                                  13315
Загальний стаж роботи за спеціальністю                                        13315
dtype: int64

In [6]:
# Список колонок, які мають дані - спосіб 2
df.columns[df.notna().any()].to_list()

['Timestamp',
 'Ви працюєте зараз в ІТ?',
 'Де ви зараз живете? ',
 'В якій області ви зараз живете?',
 'Зарплата у $$$ за місяць, лише ставка після сплати податків',
 'Ваша стать',
 'Ваш вік',
 'Яка у вас освіта?',
 'Чи є у вас науковий ступінь? ',
 'Знання англійської мови',
 'Оберіть вашу посаду',
 'Ваш тайтл',
 'Ваша спеціалізація',
 'Вкажіть вашу спеціалізацію',
 'Оберіть вашу спеціалізацію',
 'Ваша посада',
 'Оберіть вашу посаду2',
 'Ваша посада3',
 'Ваша посада4',
 'Ваша посада5',
 'Ваша посада6',
 'Ваша посада7',
 'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',
 'Основна мова програмування',
 'Вкажіть вашу основну спеціалізацію',
 'В якій сфері працюєте?',
 'Тип компанії',
 'Загальний стаж роботи за спеціальністю']

3. Скільки рядків та колонок мають дані? Скільки пропущених значень має кожна з колонок?

In [7]:
df.loc[df.notna().any(axis=1)].shape

(13315, 28)

In [8]:
df.isna().sum()

Timestamp                                                                         0
Ви працюєте зараз в ІТ?                                                           0
Де ви зараз живете?                                                               0
В якій області ви зараз живете?                                                1777
Зарплата у $$$ за місяць, лише ставка після сплати податків                      27
Ваша стать                                                                        0
Ваш вік                                                                           0
Яка у вас освіта?                                                                 0
Чи є у вас науковий ступінь?                                                    111
Знання англійської мови                                                           0
Оберіть вашу посаду                                                               0
Ваш тайтл                                                                         0
Ваша спеціалізація                                                            13156
Вкажіть вашу спеціалізацію                                                    10951
Оберіть вашу спеціалізацію                                                    12829
Ваша посада                                                                   13010
Оберіть вашу посаду2                                                          12755
Ваша посада3                                                                  12494
Ваша посада4                                                                  12830
Ваша посада5                                                                  13027
Ваша посада6                                                                  12962
Ваша посада7                                                                  13199
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?     8441
Основна мова програмування                                                     4255
Вкажіть вашу основну спеціалізацію                                             4256
В якій сфері працюєте?                                                            0
Тип компанії                                                                      0
Загальний стаж роботи за спеціальністю                                            0
dtype: int64

4. Які колонки мають всі значення заповненими (не мають дожного None значення)? Виведіть програмно список цих колонок.

In [9]:
df.columns[df.notnull().sum() == df.shape[0]].to_list()

['Timestamp',
 'Ви працюєте зараз в ІТ?',
 'Де ви зараз живете? ',
 'Ваша стать',
 'Ваш вік',
 'Яка у вас освіта?',
 'Знання англійської мови',
 'Оберіть вашу посаду',
 'Ваш тайтл',
 'В якій сфері працюєте?',
 'Тип компанії',
 'Загальний стаж роботи за спеціальністю']

5. Який тип мають колонки в наборі даних? Які з колонок типу object логічно на ваш погляд перетворити на числові колонки?

In [10]:
# Тип даних кожної з колонок - object, тобто string. 
# Потрібно перетворити в числові колонки: 'Зарплата у $$$ за місяць, лише ставка після сплати податків', 'Ваш вік'
df.dtypes

Timestamp                                                                     object
Ви працюєте зараз в ІТ?                                                       object
Де ви зараз живете?                                                           object
В якій області ви зараз живете?                                               object
Зарплата у $$$ за місяць, лише ставка після сплати податків                   object
Ваша стать                                                                    object
Ваш вік                                                                       object
Яка у вас освіта?                                                             object
Чи є у вас науковий ступінь?                                                  object
Знання англійської мови                                                       object
Оберіть вашу посаду                                                           object
Ваш тайтл                                                                     object
Ваша спеціалізація                                                            object
Вкажіть вашу спеціалізацію                                                    object
Оберіть вашу спеціалізацію                                                    object
Ваша посада                                                                   object
Оберіть вашу посаду2                                                          object
Ваша посада3                                                                  object
Ваша посада4                                                                  object
Ваша посада5                                                                  object
Ваша посада6                                                                  object
Ваша посада7                                                                  object
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?    object
Основна мова програмування                                                    object
Вкажіть вашу основну спеціалізацію                                            object
В якій сфері працюєте?                                                        object
Тип компанії                                                                  object
Загальний стаж роботи за спеціальністю                                        object
dtype: object

6. Трансформуйте колонки 'Ваш вік', 'Зарплата у $$$ за місяць, лише ставка після сплати податків' у тип даних float. УВАГА! Перед трансформацією подивіться, які дані містять ці колонки. Аби успішно трансформувати тип даних, треба спочатку привести рядки до того виду, який буде підходити, аби потім рядок зробити типом float.

In [11]:
# Трансформація атрибуту 'Ваш вік'
df['Ваш вік'] = df['Ваш вік'].apply(lambda x: x.replace(',', '.')).astype(float)
df['Ваш вік'].value_counts()

Ваш вік
25.0    929
27.0    879
28.0    847
26.0    835
30.0    820
29.0    790
24.0    739
32.0    690
31.0    686
23.0    671
33.0    669
22.0    604
34.0    572
35.0    540
21.0    467
36.0    425
20.0    340
37.0    328
38.0    272
39.0    222
40.0    196
19.0    166
41.0    127
42.0    103
44.0     70
45.0     59
43.0     58
18.0     52
46.0     34
47.0     21
48.0     20
49.0     20
50.0     15
53.0     11
17.0      7
51.0      6
55.0      5
52.0      5
56.0      4
57.0      3
58.0      2
63.0      1
54.0      1
60.0      1
16.0      1
29.5      1
14.0      1
Name: count, dtype: int64

In [28]:
# Трансформація атрибуту 'Зарплата у $$$ за місяць, лише ставка після сплати податків'
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].fillna('0').apply(lambda x: x.replace(',', '.')).astype(float)

In [29]:
df.dtypes

Timestamp                                                                      object
Ви працюєте зараз в ІТ?                                                        object
Де ви зараз живете?                                                            object
В якій області ви зараз живете?                                                object
Зарплата у $$$ за місяць, лише ставка після сплати податків                   float64
Ваша стать                                                                     object
Ваш вік                                                                       float64
Яка у вас освіта?                                                              object
Чи є у вас науковий ступінь?                                                   object
Знання англійської мови                                                        object
Оберіть вашу посаду                                                            object
Ваш тайтл                                                                      object
Ваша спеціалізація                                                             object
Вкажіть вашу спеціалізацію                                                     object
Оберіть вашу спеціалізацію                                                     object
Ваша посада                                                                    object
Оберіть вашу посаду2                                                           object
Ваша посада3                                                                   object
Ваша посада4                                                                   object
Ваша посада5                                                                   object
Ваша посада6                                                                   object
Ваша посада7                                                                   object
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?     object
Основна мова програмування                                                     object
Вкажіть вашу основну спеціалізацію                                             object
В якій сфері працюєте?                                                         object
Тип компанії                                                                   object
Загальний стаж роботи за спеціальністю                                         object
dtype: object

7. Це завдання з зірочкою! Нам треба транфсформувати колонку Timestamp у тип даних `datetime64[ns]`. Це не так просто як здається на першйий погляд :) Але це реальна ситуація, яка може трапитись при зборі даних в роботі аналітиком.
Я запропоную один зі способів виконати завдання, але ви можете написати по-своєму. Головне - отримати колонку - потрібного типу. 
Пропоную наступний алгоритм дій:
    1. Подивитись, які дані містяться в цій колонці. Виведіть перші і останні 5 записів. Чи однаковий формат цих даних? (спойлер: ні, бо інакше все було б просто :))
    2. Нам треба враховуючи різний формат даних перетворити рядок у колонці `Timestamp` на тип `datetime64[ns]`. Як це зробити? Для перетворення рядка на `datetime64` пропоную скористатись `datetime.datetime.strptime`.
    Для цього треба імпортувати бібліотеку `datetime`. Я пропоную написати функцію для обробки кожного окремого рядка, яка враховує довжину рядка і на основі цього застосовує різний формат даних дати.
    Як прописувати формат даних можна переглянути [тут](https://www.w3schools.com/python/python_datetime.asp).
    3. Коли функція для обробки кожного окремого рядка готова, застосуйте її для всіх даних з допомогою методу `apply`.

In [31]:
# 1. Виведення на екран перших і останніх 5-ти вартостей атрибуту Timestamp

display(
    df['Timestamp'].head(),
    df['Timestamp'].tail()
)

0    11.30.2022 10:26:37
1    11.30.2022 10:26:39
2    11.30.2022 10:26:58
3    11.30.2022 10:27:31
4    11.30.2022 10:27:34
Name: Timestamp, dtype: object

13310    01.09.2023 11:01
13311    01.09.2023 11:14
13312    01.09.2023 11:19
13313    01.09.2023 11:28
13314    01.09.2023 11:38
Name: Timestamp, dtype: object

8. Для колонок типу даних object (які такими лишились після всіх наших трансформацій) виведіть кількість унікальних значень.

9. Для колонок типу даних object виведіть топ 10 найбільш частих значень з кількістю рядків, в яких це значення зустрічається. Зробіть це для кожної колонки окремо. Наприклад, в циклі.  
Що цікавого бачите? Які висновки можна зробити? Що особисто Вас вразило?

10. Виведіть медіанну (медіана - це значення, менше якого є рівно 50% вибірки і більше якого є теж рівно 50% вибірки)
ЗП (Зарплата у $$$) для кожного рівня знання англійської. Які висновки можна зробити?

11. Є така штука як сортування значень категоріальної змінної. Нам це зараз стане в нагоді, адже рівні англійської можна посортувати. 
Давайте відсотруємо рівні англ. і тайтли. Просто запустіть код нижче і проаналізуйте, що він робить.

In [ ]:
df['Знання англійської мови'] = pd.Categorical(df['Знання англійської мови'], 
                      categories=['Elementary','Pre-Intermediate','Intermediate','Upper-Intermediate','Advanced'],
                      ordered=True)

df['Ваш тайтл'] = pd.Categorical(df['Ваш тайтл'], 
                      categories=['Intern/Trainee', 'Junior', 'Немає тайтлу', 'Middle', 'Senior', 'Tech Lead', 'Team Lead', 'Architect', 'Head', 'Manager'],
                      ordered=True)

12. Зробіть зводну таблицю, де стовпці - це 'Ваш тайтл', рядки - 'Знання англійської мови', а значення - медіанна ЗП. Які висновки можна зробити?
Тут ще для зручності можна зробити градієнтне забарвлення і відформатувати значення для легшого перегляду.

13. Виведіть результат методу describe() для топ 5 за частотою зустрічання в даних областей (В якій області ви зараз живете?). Зробіть висновки, де вигідніше жити з точки зору ЗП і чи суттєва різниця на Ваш погляд для прийняття рішення про переїзд?

14. Як зростає зарплата з роками? Для цього нам треба відформатувати колонку "Загальний стаж роботи за спеціальністю" аналогічно до того, як ми це робили для колонки 'Знання англійської мови' і потім вивести медіанні значення для кількості років стажу.

Далі тут можна зробити багато аналогічних агрегацій, проаналізувати, в який час люди заповнювали форму, хто більше отримує, Business Analyst, чи Data Analyst. Я вас заохочувати не стримувати свій інтерес і покапати ці дані далі :)